# Generated by Django 3.1 on 2020-08-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
